src/Models/BucketViewModels/CreateBucketViewModel.cs
using Aiursoft.Developer.Models.AppsViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Aiursoft.Pylon.Attributes;
using Aiursoft.Pylon.Models.Developer;

namespace Aiursoft.Developer.Models.BucketViewModels
{
    public class CreateBucketViewModel : AppLayoutModel
    {
        [Obsolete(message: "This method is only for framework", error: true)]
        public CreateBucketViewModel() { }
        public CreateBucketViewModel(DeveloperUser User) : base(User, 2)
        {
        }
        public CreateBucketViewModel(Controller c, DeveloperUser User) : base(User, 2)
        {
            c.ViewData["PartId"] = new SelectList(this.AllApps, nameof(App.AppId), nameof(App.AppName));
        }
        public void Recover(Controller c, DeveloperUser User)
        {
            this.Recover(User, 2);
            c.ViewData["PartId"] = new SelectList(this.AllApps, nameof(App.AppId), nameof(App.AppName));
        }
        [Required]
        [Display(Name = "Selete App")]
        public string AppId { get; set; }
        [Display(Name = "New bucket name")]
        [MaxLength(25)]
        [MinLength(5)]
        [Required]
        [NoSpace]
        [NoDot]
        public string NewBucketName { get; set; }
        public bool ModelStateValid { get; set; } = true;
        [Display(Name = "Open To Read")]
        public bool OpenToRead { get; set; }
        [Display(Name = "Open To Upload")]
        public bool OpenToUpload { get; set; }
    }
}

src/Models/BucketViewModels/DeleteBucketViewModel.cs
using Aiursoft.Pylon.Models.Developer;
using Aiursoft.Developer.Models.AppsViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Aiursoft.Developer.Models.BucketViewModels
{
    public class DeleteBucketViewModel : AppLayoutModel
    {

        [Obsolete(message: "This method is only for framework", error: true)]
        public DeleteBucketViewModel() { }
        public DeleteBucketViewModel(DeveloperUser User) : base(User, 2)
        {
        }
        [Display(Name = "Bucket Name")]
        public string BucketName { get; set; }
        public int FilesCount { get; set; }
        [Required]
        public string AppId { get; set; }
        [Required]
        public int BucketId { get; set; }
    }
}

src/Models/BucketViewModels/EditBucketViewModel.cs
using Aiursoft.Pylon.Models.Developer;
using Aiursoft.Pylon.Models.OSS;
using Aiursoft.Pylon.Models.OSS.ApiViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Aiursoft.Developer.Models.BucketViewModels
{
    public class EditBucketViewModel : CreateBucketViewModel
    {
        [Obsolete(message: "This method is only for framework", error: true)]
        public EditBucketViewModel() { }
        public EditBucketViewModel(DeveloperUser User, ViewBucketViewModel thisBucket) : base(User)
        {
            this.NewBucketName = thisBucket.BucketName;
            this.BucketId = thisBucket.BucketId;
            this.OpenToRead = thisBucket.OpenToRead;
            this.OpenToUpload = thisBucket.OpenToUpload;
        }
        [Required]
        public int BucketId { get; set; }
    }
}

src/Controllers/BucketController.cs
using Aiursoft.Pylon;
using Aiursoft.Pylon.Attributes;
using Aiursoft.Pylon.Exceptions;
using Aiursoft.Pylon.Models;
using Aiursoft.Pylon.Models.Developer;
using Aiursoft.Pylon.Models.OSS;
using Aiursoft.Pylon.Services.ToOSSServer;
using Aiursoft.Developer.Data;
using Aiursoft.Developer.Models;
using Aiursoft.Developer.Models.BucketViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Aiursoft.Developer.Controllers
{
    [AiurForceAuth]
    public class BucketController : Controller
    {
        private readonly UserManager<DeveloperUser> _userManager;
        private readonly SignInManager<DeveloperUser> _signInManager;
        private readonly ILogger _logger;
        private readonly DeveloperDbContext _dbContext;

        public BucketController(
        UserManager<DeveloperUser> userManager,
        SignInManager<DeveloperUser> signInManager,
        ILoggerFactory loggerFactory,
        DeveloperDbContext _context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = loggerFactory.CreateLogger<BucketController>();
            _dbContext = _context;
        }

        public async Task<IActionResult> Index()
        {
            var cuser = await GetCurrentUserAsync();
            var allBuckets = new List<Bucket>();
            foreach (var app in cuser.MyApps)
            {
                var appInfo = await ApiService.ViewMyBucketsAsync(await AppsContainer.AccessToken(app.AppId, app.AppSecret)());
                allBuckets.AddRange(appInfo.Buckets);
            }
            var model = new IndexViewModel(cuser)
            {
                AllBuckets = allBuckets
            };
            return View(model);
        }

        public async Task<IActionResult> CreateBucket(string id)//AppId
        {
            var cuser = await GetCurrentUserAsync();
            var viewModel = new CreateBucketViewModel(this, cuser)
            {
                AppId = id,
            };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateBucket([FromForm]CreateBucketViewModel model)
        {
            var cuser = await GetCurrentUserAsync();
            if (!ModelState.IsValid)
            {
                model.ModelStateValid = false;
                model.Recover(this, cuser);
                return View(model);
            }
            var app = await _dbContext.Apps.FindAsync(model.AppId);
            if (app == null)
            {
                return NotFound();
            }
            try
            {
                var token = AppsContainer.AccessToken(app.AppId, app.AppSecret);
                var result = await ApiService.CreateBucketAsync(await token(), model.NewBucketName, model.OpenToRead, model.OpenToUpload);
                return RedirectToAction(nameof(AppsController.ViewApp), "Apps", new { id = app.AppId, JustHaveUpdated = true });
            }
            catch (AiurUnexceptedResponse e)
            {
                ModelState.AddModelError(string.Empty, e.Response.message);
                model.ModelStateValid = false;
                model.Recover(this, cuser);
                return View(model);
            }
        }

        public async Task<IActionResult> EditBucket(int id)//BucketId
        {
            var cuser = await GetCurrentUserAsync();
            var bucket = await ApiService.ViewBucketDetailAsync(id);
            var model = new EditBucketViewModel(cuser, bucket)
            {
                AppId = bucket.BelongingAppId
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditBucket(EditBucketViewModel model)
        {
            var cuser = await GetCurrentUserAsync();
            if (!ModelState.IsValid)
            {
                model.ModelStateValid = false;
                model.Recover(cuser, 1);
                return View(model);
            }
            try
            {
                var app = await _dbContext.Apps.FindAsync(model.AppId);
                var token = AppsContainer.AccessToken(app.AppId, app.AppSecret);
                var bucket = await ApiService.ViewBucketDetailAsync(model.BucketId);
                if (bucket.BelongingAppId != app.AppId || app.CreaterId != cuser.Id) return Unauthorized();

                await ApiService.EditBucketAsync(await token(), model.BucketId, model.NewBucketName, model.OpenToRead, model.OpenToUpload);
                return RedirectToAction(nameof(AppsController.ViewApp), "Apps", new { id = model.AppId, JustHaveUpdated = true });
            }
            catch (AiurUnexceptedResponse e)
            {
                ModelState.AddModelError(string.Empty, e.Response.message);
                model.ModelStateValid = false;
                model.Recover(cuser, 1);
                return View(model);
            }
        }

        public async Task<IActionResult> DeleteBucket(int Id)//BucketId
        {
            var cuser = await GetCurrentUserAsync();
            var bucket = await ApiService.ViewBucketDetailAsync(Id);
            var model = new DeleteBucketViewModel(cuser)
            {
                BucketName = bucket.BucketName,
                FilesCount = bucket.FileCount,
                AppId = bucket.BelongingAppId,
                BucketId = bucket.BucketId
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteBucket([FromForm]DeleteBucketViewModel model)
        {
            if (ModelState.IsValid)
            {
                var app = await _dbContext.Apps.FindAsync(model.AppId);
                var cuser = await GetCurrentUserAsync();
                var token = AppsContainer.AccessToken(app.AppId, app.AppSecret);
                var bucket = await ApiService.ViewBucketDetailAsync(model.BucketId);
                if (bucket.BelongingAppId != app.AppId || app.CreaterId != cuser.Id)
                {
                    return Unauthorized();
                }
                await ApiService.DeleteBucketAsync(await token(), model.BucketId);
                return RedirectToAction(nameof(AppsController.ViewApp), "Apps", new { id = model.AppId });
            }
            return View(model);
        }

        private async Task<DeveloperUser> GetCurrentUserAsync()
        {
            return await _dbContext.Users.Include(t => t.MyApps).SingleOrDefaultAsync(t => t.UserName == User.Identity.Name);
        }
    }
}

src/Controllers/FilesController.cs
using Aiursoft.Pylon;
using Aiursoft.Pylon.Attributes;
using Aiursoft.Pylon.Models;
using Aiursoft.Pylon.Services.ToOSSServer;
using Aiursoft.Developer.Data;
using Aiursoft.Developer.Models;
using Aiursoft.Developer.Models.FilesViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;
using Aiursoft.Pylon.Services;
using Aiursoft.Pylon.Models.Developer;

namespace Aiursoft.Developer.Controllers
{
    [AiurForceAuth]
    public class FilesController : Controller
    {
        public readonly UserManager<DeveloperUser> _userManager;
        public readonly SignInManager<DeveloperUser> _signInManager;
        public readonly ILogger _logger;
        public DeveloperDbContext _dbContext;

        public FilesController(
        UserManager<DeveloperUser> userManager,
        SignInManager<DeveloperUser> signInManager,
        ILoggerFactory loggerFactory,
        DeveloperDbContext _context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = loggerFactory.CreateLogger<FilesController>();
            _dbContext = _context;
        }

        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();
            var model = new IndexViewModel(user);
            return View(model);
        }

        public async Task<IActionResult> ViewFiles(int id)//Bucket Id
        {
            var cuser = await GetCurrentUserAsync();
            var bucketInfo = await ApiService.ViewBucketDetailAsync(id);
            var app = await _dbContext.Apps.FindAsync(bucketInfo.BelongingAppId);
            var files = await ApiService.ViewAllFilesAsync(await AppsContainer.AccessToken(app.AppId, app.AppSecret)(), id);
            var model = new ViewFilesViewModel(cuser)
            {
                BucketId = files.BucketId,
                AllFiles = files.AllFiles,
                AppId = app.AppId,
                OpenToRead = bucketInfo.OpenToRead,
                BucketName = bucketInfo.BucketName
            };
            return View(model);
        }

        public async Task<IActionResult> GenerateLink(int id)
        {
            var cuser = await GetCurrentUserAsync();
            var fileinfo = await ApiService.ViewOneFileAsync(id);
            var bucketInfo = await ApiService.ViewBucketDetailAsync(fileinfo.File.BucketId);
            var app = await _dbContext.Apps.FindAsync(bucketInfo.BelongingAppId);
            if (bucketInfo.BelongingAppId != app.AppId)
            {
                return Unauthorized();
            }
            var secret = await SecretService.GenerateAsync(id, await AppsContainer.AccessToken(app.AppId, app.AppSecret)());
            var model = new GenerateLinkViewModel(cuser)
            {
                Address = secret.Value,
                BucketId = bucketInfo.BucketId
            };
            return View(model);
        }

        public async Task<IActionResult> DeleteFile(int id)
        {
            var cuser = await GetCurrentUserAsync();
            var fileinfo = await ApiService.ViewOneFileAsync(id);
            var bucketInfo = await ApiService.ViewBucketDetailAsync(fileinfo.File.BucketId);
            var app = await _dbContext.Apps.FindAsync(bucketInfo.BelongingAppId);

            if (bucketInfo.BelongingAppId != app.AppId)
            {
                return Unauthorized();
            }
            var model = new DeleteFileViewModel(cuser)
            {
                FileName = fileinfo.File.RealFileName,
                FileId = fileinfo.File.FileKey,
                BucketId = fileinfo.File.BucketId
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteFile(DeleteFileViewModel model)
        {
            var cuser = await GetCurrentUserAsync();
            if (!ModelState.IsValid)
            {
                model.Recover(cuser, 3);
                return View(model);
            }
            var fileinfo = await ApiService.ViewOneFileAsync(model.FileId);
            var bucketInfo = await ApiService.ViewBucketDetailAsync(fileinfo.File.BucketId);
            var app = await _dbContext.Apps.FindAsync(bucketInfo.BelongingAppId);

            if (fileinfo == null || bucketInfo.BelongingAppId != app.AppId || fileinfo.File.BucketId != bucketInfo.BucketId)
            {
                return Unauthorized();
            }
            await ApiService.DeleteFileAsync(await AppsContainer.AccessToken(app.AppId, app.AppSecret)(), model.FileId, bucketInfo.BucketId);
            return RedirectToAction(nameof(ViewFiles), new
            {
                id = bucketInfo.BucketId
            });
        }
        public async Task<IActionResult> UploadFile(int id)//BucketId
        {
            var cuser = await GetCurrentUserAsync();
            var bucket = await ApiService.ViewBucketDetailAsync(id);
            var viewModel = new UploadFileViewModel(cuser)
            {
                BucketId = bucket.BucketId,
                AppId = bucket.BelongingAppId,
                BucketName = bucket.BucketName,
            };
            return View(viewModel);
        }

        [HttpPost]
        [ContainsValidFile]
        public async Task<IActionResult> UploadFile(UploadFileViewModel model)
        {
            var cuser = await GetCurrentUserAsync();
            if (!ModelState.IsValid)
            {
                model.Recover(cuser, 3);
                model.ModelStateValid = false;
                return View(model);
            }
            var app = await _dbContext.Apps.FindAsync(model.AppId);
            string accessToken = await AppsContainer.AccessToken(app.AppId, app.AppSecret)();
            var file = Request.Form.Files.First();
            await StorageService.SaveToOSS(file, model.BucketId, model.AliveDays, SaveFileOptions.SourceName, accessToken);
            return RedirectToAction(nameof(ViewFiles), new { id = model.BucketId });
        }

        private async Task<DeveloperUser> GetCurrentUserAsync()
        {
            return await _dbContext.Users.Include(t => t.MyApps).SingleOrDefaultAsync(t => t.UserName == User.Identity.Name);
        }
    }
}

src/Views/Bucket/CreateBucket.cshtml
@model Aiursoft.Developer.Models.BucketViewModels.CreateBucketViewModel
@{
    ViewData["Title"] = "Create New Bucket";
    Layout = "_AppLayout";
}

<div class="container-fluid">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-controller="Apps" asp-action="Index">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-controller="Bucket" asp-action="Index">Buckets</a>
        </li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
    @if (!Model.ModelStateValid)
    {
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            <strong>Invalid Input!</strong>
            <div asp-validation-summary="All"></div>
        </div>
    }

    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-inbox"></i>
            New Bucket Info
        </div>
        <div class="card-body">
            <div class="col-xs-12">
                    <form asp-controller="Bucket" asp-action="CreateBucket" method="post" class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="AppId"></label>
                                <select asp-for="AppId" class="form-control" asp-items="@ViewBag.PartId"></select>
                                <span asp-validation-for="AppId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="NewBucketName"></label>
                                <input asp-for="NewBucketName" type="text" class="form-control" placeholder="Enter your new bucket name...">
                                <span asp-validation-for="NewBucketName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="switch success">
                                        <input asp-for="OpenToRead" type="checkbox">
                                        <label asp-for="OpenToRead"></label>
                                    </div>
                                </div>
                                <div class="col-md-9">
                                    <p>Allow anyone even without access token to access all your files in that bucket.</p>
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="switch warning">
                                        <input type="checkbox" asp-for="OpenToUpload">
                                        <label asp-for="OpenToUpload"></label>
                                    </div>
                                </div>
                                <div class="col-md-9">
                                    <p>Allow anyone even without access token to upload files to that bucket.</p>
                                </div>
                            </div>
                            <hr />
                        </div>

                        <div class="col-xs-12 margin-top-30">
                            <button type="submit" data-disable-with="Creating..." class="btn btn-primary btn">Create</button>
                            <button type="reset" class="btn btn-danger btn" id="cleartoasts">Clear</button>
                            @if (!string.IsNullOrEmpty(Model.AppId))
                            {
                                <a class="btn btn-info btn" asp-controller="Apps" asp-action="ViewApp" asp-route-id="@Model.AppId">Back to app</a>
                            }
                            else
                            {
                                <a class="btn btn-info btn" asp-controller="Bucket" asp-action="Index">All Buckets</a>
                            }
                        </div>
                    </form>
            </div>
        </div>
    </div>
</div>

src/Views/Bucket/DeleteBucket.cshtml
@model Aiursoft.Developer.Models.BucketViewModels.DeleteBucketViewModel
@{
    ViewData["Title"] = "Delete" + Model.BucketName;
    Layout = "_AppLayout";
}
<div class="container-fluid">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-controller="Apps" asp-action="Index">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-controller="Bucket" asp-action="Index">Buckets</a>
        </li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        <strong>Caution!</strong> You are about to delete "@Model.BucketName"! If you are confirmed to continue, you will lose all @Model.FilesCount files in the bucket! This process is not recoverable!
    </div>

    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-trash ico"></i>
            New Bucket Info
        </div>
        <div class="card-body">
            <div class="col-xs-12">
                <form asp-controller="Bucket" asp-action="DeleteBucket" method="post">
                    <input type="hidden" asp-for="AppId" />
                    <input type="hidden" asp-for="BucketId" />
                    <div class="box-content bordered danger">
                        <h4 class="box-title">Delete Bucket</h4>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label asp-for="BucketName"></label>
                                    <input asp-for="BucketName" readonly="readonly" type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-md-12 margin-top-30">
                                <a class="btn btn-success" asp-controller="Apps" asp-action="ViewApp" asp-route-id="@Model.AppId">Back to App</a>
                                <a class="btn btn-info" asp-controller="Files" asp-action="ViewFiles" asp-route-id="@Model.BucketId">View Files</a>
                                <button class="btn btn-danger btn" data-disable-with="Deleting..." type="submit">Confirm to delete</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

src/Views/Bucket/EditBucket.cshtml
@model Aiursoft.Developer.Models.BucketViewModels.EditBucketViewModel
@{
    ViewData["Title"] = "Edit Bucket" + Model.NewBucketName;
    Layout = "_AppLayout";
}

<div class="container-fluid">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-controller="Apps" asp-action="Index">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-controller="Bucket" asp-action="Index">Buckets</a>
        </li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
    @if (!Model.ModelStateValid)
    {
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            <strong>Invalid Input!</strong>
            <div asp-validation-summary="All"></div>
        </div>
    }

    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-pencil"></i>
            New Bucket Info
        </div>
        <div class="card-body">
            <div class="col-xs-12">
                <form asp-controller="Bucket" asp-action="EditBucket" method="post" class="row">
                    <input type="hidden" asp-for="AppId" />
                    <input type="hidden" asp-for="BucketId" />
                    <div class="col-md-4 col-xs-12">
                        <div class="form-group">
                            <label asp-for="NewBucketName"></label>
                            <input asp-for="NewBucketName" type="text" class="form-control" placeholder="Enter your new bucket name...">
                            <span asp-validation-for="NewBucketName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="switch success">
                                    <input asp-for="OpenToRead" type="checkbox">
                                    <label asp-for="OpenToRead"></label>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <p>Allow anyone even without access token to access all your files in that bucket.</p>
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-md-3">
                                <div class="switch warning">
                                    <input type="checkbox" asp-for="OpenToUpload">
                                    <label asp-for="OpenToUpload"></label>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <p>Allow anyone even without access token to upload files to that bucket.</p>
                            </div>
                        </div>
                        <hr />
                    </div>

                    <div class="col-xs-12 margin-top-30">
                        <button class="btn btn-primary" data-disable-with="Updating..." type="submit">Update</button>
                        <a class="btn btn-warning" asp-controller="Files" asp-action="ViewFiles" asp-route-id="@Model.BucketId">View Files</a>
                        <a class="btn btn-info" asp-controller="Apps" asp-action="ViewApp" asp-route-id="@Model.AppId">Back to app</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

src/Views/Bucket/Index.cshtml
@model Aiursoft.Developer.Models.BucketViewModels.IndexViewModel
@{
    ViewData["Title"] = "All Buckets";
    Layout = "_AppLayout";
}

<div class="container-fluid">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-controller="Apps" asp-action="Index">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-controller="Bucket" asp-action="Index">Buckets</a>
        </li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-inbox ico"></i>
            All Buckets Of Object Storage Service
        </div>
        <div class="card-body">
            <div class="col-xs-12">
                <table class="table table-striped datatable">
                    <thead>
                        <tr>
                            <th>Bucket ID</th>
                            <th>Bucket Name</th>
                            <th>Files count</th>
                            <th>Open to read</th>
                            <th>Open to upload</th>
                            <th style="width: 460px">Operation</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var buc in Model.AllBuckets)
                        {
                            <tr>
                                <td>@buc.BucketId</td>
                                <td>@buc.BucketName</td>
                                <td>@buc.FileCount</td>
                                <td>
                                    <div class="switch success">
                                        <input type="checkbox" asp-for="@buc.OpenToRead" readonly="readonly">
                                        <label></label>
                                    </div>
                                </td>
                                <td>
                                    <div class="switch warning">
                                        <input type="checkbox" asp-for="@buc.OpenToUpload" readonly="readonly">
                                        <label></label>
                                    </div>
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <a asp-controller="Bucket" asp-action="EditBucket" asp-route-id="@buc.BucketId" class="btn btn-secondary waves-effect waves-light">Edit</a>
                                        <a asp-controller="Bucket" asp-action="DeleteBucket" asp-route-id="@buc.BucketId" class="btn btn-danger waves-effect waves-light">Delete</a>
                                        <a asp-controller="Files" asp-action="ViewFiles" asp-route-id="@buc.BucketId" class="btn btn-info waves-effect waves-light">View Files</a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="col-md-12 margin-top-30">
                    <a asp-controller="Bucket" asp-action="CreateBucket" class="btn btn-success">Create New Bucket</a>
                </div>
            </div>
        </div>
    </div>
</div>