src/Models/FilesViewModels/DeleteFileViewModel.cs
using Aiursoft.Pylon.Models.Developer;
using Aiursoft.Developer.Models.AppsViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Aiursoft.Developer.Models.FilesViewModels
{
    public class DeleteFileViewModel : AppLayoutModel
    {

        [Obsolete(message: "This method is only for framework", error: true)]
        public DeleteFileViewModel() { }
        public DeleteFileViewModel(DeveloperUser User) : base(User, 3) { }
        [Display(Name = "File Name")]
        public string FileName { get; set; }
        public int FileId { get; set; }

        public int BucketId { get; set; }
    }
}

src/Models/FilesViewModels/GenerateLinkViewModel.cs
using Aiursoft.Developer.Models.AppsViewModels;
using Aiursoft.Pylon.Models.Developer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Aiursoft.Developer.Models.FilesViewModels
{
    public class GenerateLinkViewModel : AppLayoutModel
    {
        [Obsolete(message: "This method is only for framework", error: true)]
        public GenerateLinkViewModel() { }
        public GenerateLinkViewModel(DeveloperUser User) : base(User, 3) { }
        public string Address { get; set; }
        public int BucketId { get; set; }
    }
}

src/Models/FilesViewModels/UploadFileViewModel.cs
using Aiursoft.Pylon.Models.Developer;
using Aiursoft.Pylon.Models.OSS;
using Aiursoft.Developer.Models.AppsViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Aiursoft.Developer.Models.FilesViewModels
{
    public class UploadFileViewModel : AppLayoutModel
    {
        [Obsolete(message: "This method is only for framework", error: true)]
        public UploadFileViewModel() { }
        public UploadFileViewModel(DeveloperUser User) : base(User, 3)
        {
        }
        [Required]
        public virtual string AppId { get; set; }
        public virtual string BucketName { get; set; }
        [Required]
        public virtual int BucketId { get; set; }

        public virtual bool ModelStateValid { get; set; } = true;
        [Required]
        [Range(1, 365)]
        [Display(Name = "Alive Days")]
        public virtual int AliveDays { get; set; }
    }
}

src/Models/FilesViewModels/ViewFilesViewModel.cs
using Aiursoft.Pylon;
using Aiursoft.Pylon.Models.Developer;
using Aiursoft.Pylon.Models.OSS;
using Aiursoft.Pylon.Models.OSS.ApiViewModels;
using Aiursoft.Developer.Models.AppsViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Aiursoft.Developer.Models.FilesViewModels
{
    public class ViewFilesViewModel : AppLayoutModel
    {
        [Obsolete(message: "This method is only for framework", error: true)]
        public ViewFilesViewModel() { }
        public ViewFilesViewModel(DeveloperUser User) : base(User, 3) { }
        public virtual int BucketId { get; set; }
        public virtual string BucketName { get; set; }
        public IEnumerable<OSSFile> AllFiles { get; set; }
        public virtual string AppId { get; set; }
        public virtual bool OpenToRead { get; set; }
    }
}

src/Controllers/AppsController.cs
using Aiursoft.Pylon;
using Aiursoft.Pylon.Attributes;
using Aiursoft.Pylon.Models;
using Aiursoft.Pylon.Models.Developer;
using Aiursoft.Pylon.Services;
using Aiursoft.Pylon.Services.ToOSSServer;
using Aiursoft.Developer.Data;
using Aiursoft.Developer.Models;
using Aiursoft.Developer.Models.AppsViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Aiursoft.Developer.Controllers
{
    [AiurForceAuth]
    public class AppsController : Controller
    {
        private readonly UserManager<DeveloperUser> _userManager;
        private readonly SignInManager<DeveloperUser> _signInManager;
        private readonly ILogger _logger;
        private readonly DeveloperDbContext _dbContext;

        public AppsController(
        UserManager<DeveloperUser> userManager,
        SignInManager<DeveloperUser> signInManager,
        ILoggerFactory loggerFactory,
        DeveloperDbContext _context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = loggerFactory.CreateLogger<AppsController>();
            _dbContext = _context;
        }

        public async Task<IActionResult> Index()
        {
            var cuser = await GetCurrentUserAsync();
            var model = new IndexViewModel(cuser);
            return View(model);
        }

        public async Task<IActionResult> AllApps()
        {
            var cuser = await GetCurrentUserAsync();
            var model = new AllAppsViewModel(cuser)
            {
                AllApps = _dbContext.Apps.Where(t => t.CreaterId == cuser.Id)
            };
            return View(model);
        }

        public async Task<IActionResult> CreateApp()
        {
            var cuser = await GetCurrentUserAsync();
            var model = new CreateAppViewModel(cuser);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateApp(CreateAppViewModel model)
        {
            var cuser = await GetCurrentUserAsync();
            if (!ModelState.IsValid)
            {
                model.ModelStateValid = false;
                model.Recover(cuser, 1);
                return View(model);
            }
            string iconPath = string.Empty;
            if (Request.Form.Files.Count == 0 || Request.Form.Files.First().Length < 1)
            {
                iconPath = Values.DeveloperServerAddress + "/images/appdefaulticon.png";
            }
            else
            {
                iconPath = await StorageService.SaveToOSS(Request.Form.Files.First(), Values.AppsIconBucketId, 365);
            }

            var _newApp = new App(cuser.Id, model.AppName, model.AppDescription, model.AppCategory, model.AppPlatform)
            {
                CreaterId = cuser.Id,
                AppIconAddress = iconPath
            };
            _dbContext.Apps.Add(_newApp);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(ViewApp), new { id = _newApp.AppId });
        }

        public async Task<IActionResult> ViewApp(string id, bool JustHaveUpdated = false)
        {
            var app = await _dbContext.Apps.FindAsync(id);
            if (app == null)
            {
                return NotFound();
            }
            var cuser = await GetCurrentUserAsync();
            var model = await ViewAppViewModel.SelfCreateAsync(cuser, app, _dbContext);
            model.JustHaveUpdated = JustHaveUpdated;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ViewApp(ViewAppViewModel model)
        {
            var cuser = await GetCurrentUserAsync();
            if (!ModelState.IsValid)
            {
                model.ModelStateValid = false;
                await model.Recover(cuser, await _dbContext.Apps.FindAsync(model.AppId), _dbContext);
                return View(model);
            }
            var target = await _dbContext.Apps.FindAsync(model.AppId);
            if (target == null)
            {
                return NotFound();
            }
            else if (target.CreaterId != cuser.Id)
            {
                return new UnauthorizedResult();
            }
            target.AppName = model.AppName;
            target.AppDescription = model.AppDescription;
            target.EnableOAuth = model.EnableOAuth;
            target.ForceInputPassword = model.ForceInputPassword;
            target.ForceConfirmation = model.ForceConfirmation;
            target.DebugMode = model.DebugMode;
            target.PrivacyStatementUrl = model.PrivacyStatementUrl;
            target.LicenseUrl = model.LicenseUrl;
            target.AppDomain = model.AppDomain;
            target.ViewOpenId = model.ViewOpenId;
            target.ViewPhoneNumber = model.ViewPhoneNumber;
            target.ChangePhoneNumber = model.ChangePhoneNumber;
            target.ConfirmEmail = model.ConfirmEmail;
            target.ChangeBasicInfo = model.ChangeBasicInfo;
            target.ChangePassword = model.ChangePassword;
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(ViewApp), new { id = target.AppId, JustHaveUpdated = true });
        }

        public async Task<IActionResult> DeleteApp(string id)
        {
            var cuser = await GetCurrentUserAsync();
            var _target = await _dbContext.Apps.FindAsync(id);
            if (_target.CreaterId != cuser.Id)
            {
                return new UnauthorizedResult();
            }
            var model = new DeleteAppViewModel(cuser)
            {
                AppId = _target.AppId,
                AppName = _target.AppName
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteApp(DeleteAppViewModel model)
        {
            var cuser = await GetCurrentUserAsync();
            if (!ModelState.IsValid)
            {
                model.Recover(cuser, 1);
                return View(model);
            }
            var target = await _dbContext.Apps.FindAsync(model.AppId);
            if (target == null)
            {
                return NotFound();
            }
            else if (target.CreaterId != cuser.Id)
            {
                return new UnauthorizedResult();
            }
            await ApiService.DeleteAppAsync(await AppsContainer.AccessToken(target.AppId, target.AppSecret)(), target.AppId);
            _dbContext.Apps.Remove(target);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(AllApps));

        }

        private async Task<DeveloperUser> GetCurrentUserAsync()
        {
            return await _dbContext.Users.Include(t => t.MyApps).SingleOrDefaultAsync(t => t.UserName == User.Identity.Name);
        }

        [HttpPost]
        [ContainsValidFile]
        public async Task<IActionResult> ChangeIcon(string AppId)
        {
            if(!ModelState.IsValid)
            {
                return RedirectToAction(nameof(ViewApp), new { id = AppId, JustHaveUpdated = true });
            }
            var appExists = await _dbContext.Apps.FindAsync(AppId);
            appExists.AppIconAddress = await StorageService.SaveToOSS(Request.Form.Files.First(), Values.AppsIconBucketId, 365);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(ViewApp), new { id = AppId, JustHaveUpdated = true });
        }
    }
}

src/Controllers/FilesController.cs
using Aiursoft.Pylon;
using Aiursoft.Pylon.Attributes;
using Aiursoft.Pylon.Models;
using Aiursoft.Pylon.Services.ToOSSServer;
using Aiursoft.Developer.Data;
using Aiursoft.Developer.Models;
using Aiursoft.Developer.Models.FilesViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;
using Aiursoft.Pylon.Services;
using Aiursoft.Pylon.Models.Developer;

namespace Aiursoft.Developer.Controllers
{
    [AiurForceAuth]
    public class FilesController : Controller
    {
        public readonly UserManager<DeveloperUser> _userManager;
        public readonly SignInManager<DeveloperUser> _signInManager;
        public readonly ILogger _logger;
        public DeveloperDbContext _dbContext;

        public FilesController(
        UserManager<DeveloperUser> userManager,
        SignInManager<DeveloperUser> signInManager,
        ILoggerFactory loggerFactory,
        DeveloperDbContext _context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = loggerFactory.CreateLogger<FilesController>();
            _dbContext = _context;
        }

        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();
            var model = new IndexViewModel(user);
            return View(model);
        }

        public async Task<IActionResult> ViewFiles(int id)//Bucket Id
        {
            var cuser = await GetCurrentUserAsync();
            var bucketInfo = await ApiService.ViewBucketDetailAsync(id);
            var app = await _dbContext.Apps.FindAsync(bucketInfo.BelongingAppId);
            var files = await ApiService.ViewAllFilesAsync(await AppsContainer.AccessToken(app.AppId, app.AppSecret)(), id);
            var model = new ViewFilesViewModel(cuser)
            {
                BucketId = files.BucketId,
                AllFiles = files.AllFiles,
                AppId = app.AppId,
                OpenToRead = bucketInfo.OpenToRead,
                BucketName = bucketInfo.BucketName
            };
            return View(model);
        }

        public async Task<IActionResult> GenerateLink(int id)
        {
            var cuser = await GetCurrentUserAsync();
            var fileinfo = await ApiService.ViewOneFileAsync(id);
            var bucketInfo = await ApiService.ViewBucketDetailAsync(fileinfo.File.BucketId);
            var app = await _dbContext.Apps.FindAsync(bucketInfo.BelongingAppId);
            if (bucketInfo.BelongingAppId != app.AppId)
            {
                return Unauthorized();
            }
            var secret = await SecretService.GenerateAsync(id, await AppsContainer.AccessToken(app.AppId, app.AppSecret)());
            var model = new GenerateLinkViewModel(cuser)
            {
                Address = secret.Value,
                BucketId = bucketInfo.BucketId
            };
            return View(model);
        }

        public async Task<IActionResult> DeleteFile(int id)
        {
            var cuser = await GetCurrentUserAsync();
            var fileinfo = await ApiService.ViewOneFileAsync(id);
            var bucketInfo = await ApiService.ViewBucketDetailAsync(fileinfo.File.BucketId);
            var app = await _dbContext.Apps.FindAsync(bucketInfo.BelongingAppId);

            if (bucketInfo.BelongingAppId != app.AppId)
            {
                return Unauthorized();
            }
            var model = new DeleteFileViewModel(cuser)
            {
                FileName = fileinfo.File.RealFileName,
                FileId = fileinfo.File.FileKey,
                BucketId = fileinfo.File.BucketId
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteFile(DeleteFileViewModel model)
        {
            var cuser = await GetCurrentUserAsync();
            if (!ModelState.IsValid)
            {
                model.Recover(cuser, 3);
                return View(model);
            }
            var fileinfo = await ApiService.ViewOneFileAsync(model.FileId);
            var bucketInfo = await ApiService.ViewBucketDetailAsync(fileinfo.File.BucketId);
            var app = await _dbContext.Apps.FindAsync(bucketInfo.BelongingAppId);

            if (fileinfo == null || bucketInfo.BelongingAppId != app.AppId || fileinfo.File.BucketId != bucketInfo.BucketId)
            {
                return Unauthorized();
            }
            await ApiService.DeleteFileAsync(await AppsContainer.AccessToken(app.AppId, app.AppSecret)(), model.FileId, bucketInfo.BucketId);
            return RedirectToAction(nameof(ViewFiles), new
            {
                id = bucketInfo.BucketId
            });
        }
        public async Task<IActionResult> UploadFile(int id)//BucketId
        {
            var cuser = await GetCurrentUserAsync();
            var bucket = await ApiService.ViewBucketDetailAsync(id);
            var viewModel = new UploadFileViewModel(cuser)
            {
                BucketId = bucket.BucketId,
                AppId = bucket.BelongingAppId,
                BucketName = bucket.BucketName,
            };
            return View(viewModel);
        }

        [HttpPost]
        [ContainsValidFile]
        public async Task<IActionResult> UploadFile(UploadFileViewModel model)
        {
            var cuser = await GetCurrentUserAsync();
            if (!ModelState.IsValid)
            {
                model.Recover(cuser, 3);
                model.ModelStateValid = false;
                return View(model);
            }
            var app = await _dbContext.Apps.FindAsync(model.AppId);
            string accessToken = await AppsContainer.AccessToken(app.AppId, app.AppSecret)();
            var file = Request.Form.Files.First();
            await StorageService.SaveToOSS(file, model.BucketId, model.AliveDays, SaveFileOptions.SourceName, accessToken);
            return RedirectToAction(nameof(ViewFiles), new { id = model.BucketId });
        }

        private async Task<DeveloperUser> GetCurrentUserAsync()
        {
            return await _dbContext.Users.Include(t => t.MyApps).SingleOrDefaultAsync(t => t.UserName == User.Identity.Name);
        }
    }
}

src/Views/Files/DeleteFile.cshtml
@model Aiursoft.Developer.Models.FilesViewModels.DeleteFileViewModel
@{
    ViewData["Title"] = "Delete" + Model.FileName;
    Layout = "_AppLayout";
}

<div class="container-fluid">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-controller="Apps" asp-action="Index">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-controller="Files" asp-action="Index">Files</a>
        </li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        <strong>Caution!</strong> You are about to delete "@Model.FileName"! If you are confirmed to continue, you will lose this file. This process is not recoverable!
    </div>
    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-trash ico"></i>
            Delete File
        </div>
        <div class="card-body">
            <div class="col-xs-12">
                <form asp-controller="Files" asp-action="DeleteFile" method="post">
                    <input type="hidden" asp-for="FileId" />
                    <div class="box-content bordered danger">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label asp-for="FileName"></label>
                                    <input asp-for="FileName" readonly="readonly" type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-md-12 margin-top-30">
                                <a class="btn btn-info" asp-controller="Files" asp-action="ViewFiles" asp-route-id="@Model.BucketId">Back to files</a>
                                <button class="btn btn-danger" data-disable-with="Deleting..." type="submit">Confirm to delete</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

src/Views/Files/GenerateLink.cshtml
@model Aiursoft.Developer.Models.FilesViewModels.GenerateLinkViewModel
@{
    ViewData["Title"] = "One Time Link";
    Layout = "_AppLayout";
}

<div class="container-fluid">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-controller="Apps" asp-action="Index">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-controller="Files" asp-action="Index">Files</a>
        </li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        <strong>Caution!</strong> Once you clicked 'Open' button, the link will be deactivated and can not be used again!
    </div>
    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-trash ico"></i>
            One Time Link
        </div>
        <div class="card-body">
            <div class="col-xs-12">
                <div class="box-content bordered danger">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="Address"></label>
                                <input value="@(Values.OssServerAddress)/download/fromsecret?sec=@Model.Address" readonly="readonly" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-12 margin-top-30">
                            <a class="btn btn-success waves-effect waves-light" href="#" data-toggle="tooltip" data-trigger="click" title="copied!" data-clipboard-text="@(Values.OssServerAddress)/download/fromsecret?sec=@Model.Address">Copy link</a>
                            <a class="btn btn-danger" href="@(Values.OssServerAddress)/download/fromsecret?sec=@Model.Address" target="_blank">Open Link</a>
                            <a class="btn btn-info" asp-controller="Files" asp-action="ViewFiles" asp-route-id="@Model.BucketId">Back to files</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/Views/Files/Index.cshtml
@model Aiursoft.Developer.Models.FilesViewModels.IndexViewModel
@{
    ViewData["Title"] = "Dashboard";
    Layout = "_AppLayout";
}
<div class="container-fluid">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
    <div class="row">
        <div class="col-12">
            <h1>Files</h1>
            <p>**Place some introduction!**</p>
        </div>
    </div>
</div>

src/Views/Files/UploadFile.cshtml
@model Aiursoft.Developer.Models.FilesViewModels.UploadFileViewModel
@{
    ViewData["Title"] = "Upload new file";
    Layout = "_AppLayout";
}

<div class="container-fluid">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-controller="Apps" asp-action="Index">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-controller="Files" asp-action="Index">Files</a>
        </li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
    @if (!Model.ModelStateValid)
    {
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            <strong>Invalid Input!</strong>
            <div asp-validation-summary="All"></div>
        </div>
    }
    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-upload"></i>
            Upload File To @Model.BucketName
        </div>
        <div class="card-body">
            <div class="col-xs-12">
                <form class="box-content" asp-controller="Files" asp-action="UploadFile" method="post" enctype="multipart/form-data">
                    <input type="hidden" asp-for="AppId" />
                    <input type="hidden" asp-for="BucketId" />
                    <input type="file" name="file" class="dropify" data-max-file-size="1000M" />
                    <p class="help margin-top-10">Only 1000Mb max.</p>
                    <div class="form-group">
                        <label asp-for="AliveDays"></label>
                        <input class="form-control" asp-for="AliveDays" type="number" placeholder="Enter the alive time (days) of the file..." />
                        <span asp-validation-for="AliveDays" class="text-danger"></span>
                    </div>
                    <div class="margin-top-30">
                        <button type="submit" data-disable-with="Uploading..." class="btn btn-primary">Upload</button>
                        <a class="btn btn-info" asp-controller="Files" asp-action="ViewFiles" asp-route-id="@Model.BucketId">Back to files</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section css{
    <link href="@Values.CdnServerAddress/node_modules/dropify/dist/css/dropify.css" rel="stylesheet">
}
@section js{
    <script src="@Values.CdnServerAddress/node_modules/dropify/dist/js/dropify.js"></script>
    <script>
        $(document).ready(function () {
            $('.dropify').dropify();
        });
    </script>
}

src/Views/Files/ViewFiles.cshtml
@model Aiursoft.Developer.Models.FilesViewModels.ViewFilesViewModel
@{
    ViewData["Title"] = "All files";
    Layout = "_AppLayout";
}

<div class="container-fluid">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-controller="Apps" asp-action="Index">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-controller="Files" asp-action="Index">Files</a>
        </li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-database ico"></i>
            Files of @Model.BucketName (Top 200)
        </div>
        <div class="card-body">
            <div class="col-xs-12">
                <table class="table table-striped datatable">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Size(Kb)</th>
                            <th>Downloads</th>
                            <th>Deadline</th>
                            <th>Download</th>
                            <th>Danger Zone</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var file in Model.AllFiles)
                        {
                            <tr>
                                <td>@file.FileKey</td>
                                <td>@file.RealFileName</td>
                                <td>@string.Format("{0:N}", Math.Round(d: (decimal)file.JFileSize / 1024, decimals: 2))</td>
                                <td>@file.DownloadTimes</td>
                                <td>@((file.UploadTime + new TimeSpan(file.AliveDays, 0, 0, 0)).ToShortDateString())</td>
                                @if (Model.OpenToRead)
                                {
                                    <td>
                                        <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                                            <a href="@file.GetInternetPath?sd=true" target="_blank" class="btn btn-secondary">Download</a>
                                            <div class="btn-group" role="group">
                                                <button id="btnGroupDrop1" type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    More
                                                </button>
                                                <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                                                    <a class="dropdown-item" href="@file.GetInternetPath" target="_blank">Open</a>
                                                    <a class="dropdown-item" href="#" data-toggle="tooltip" data-trigger="click" title="copied!" data-clipboard-text="@file.GetInternetPath">Copy link</a>
                                                    <a class="dropdown-item" asp-controller="Files" asp-action="GenerateLink" asp-route-id="@file.FileKey" target="_blank">Get One-time link</a>
                                                </div>
                                            </div>
                                        </div>
                                        @*<div class="btn-group">
                                                <a class="btn btn-warning waves-effect waves-light" href="@file.GetInternetPath?sd=true" target="_blank">Download</a>
                                                <a class="btn btn-info waves-effect waves-light" href="@file.GetInternetPath" target="_blank">Open</a>
                                                <a class="btn btn-success waves-effect waves-light" href="#" data-toggle="tooltip" data-trigger="click" title="copied!" data-clipboard-text="@file.GetInternetPath">Copy link</a>
                                            </div>*@
                                    </td>
                                }
                                <td>
                                    <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                                        <a class="btn btn-danger waves-effect waves-light" asp-controller="Files" asp-action="DeleteFile" asp-route-id="@file.FileKey">Delete</a>
                                        <div class="btn-group" role="group">
                                            <button id="btnGroupDrop1" type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                                            <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                                                <a class="dropdown-item" href="@file.GetInternetPath" target="_blank">Rename</a>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="mt-3">
                    <a asp-controller="Files" asp-action="UploadFile" asp-route-id="@Model.BucketId" class="btn btn-success">Upload new file</a>
                    <a asp-controller="Apps" asp-action="ViewApp" asp-route-id="@Model.AppId" class="btn btn-info">Back to App</a>
                    <a asp-controller="Bucket" asp-action="Index" class="btn btn-secondary">Back to All buckets</a>
                </div>

            </div>
        </div>
    </div>
</div>